import os
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import dotenv_loader  # noqa: E402


class LoadEnvFile(unittest.TestCase):
    def write(self, text):
        tmp = tempfile.NamedTemporaryFile("w", suffix=".env", delete=False)
        tmp.write(text)
        tmp.close()
        self.addCleanup(os.unlink, tmp.name)
        return Path(tmp.name)

    def tearDown(self):
        for key in ("FEEDBACK_WEBHOOK_URL", "FEEDBACK_ADMIN_KEY", "QUOTED", "ALREADY_SET"):
            os.environ.pop(key, None)

    def test_reads_the_format_ai_studio_writes(self):
        path = self.write('# Environment Variables\n# Generated by AI Studio Manager\n\n'
                          '# Secret: FEEDBACK_WEBHOOK_URL\n'
                          'FEEDBACK_WEBHOOK_URL=https://example.com/hook\n'
                          'FEEDBACK_ADMIN_KEY=abc123\n'
                          'QUOTED="a value with spaces"\n')
        applied = dotenv_loader.load(path)
        self.assertEqual(os.environ["FEEDBACK_WEBHOOK_URL"], "https://example.com/hook")
        self.assertEqual(os.environ["FEEDBACK_ADMIN_KEY"], "abc123")
        self.assertEqual(os.environ["QUOTED"], "a value with spaces")
        self.assertEqual(set(applied), {"FEEDBACK_WEBHOOK_URL", "FEEDBACK_ADMIN_KEY", "QUOTED"})

    def test_a_real_environment_variable_wins(self):
        os.environ["ALREADY_SET"] = "from shell"
        dotenv_loader.load(self.write("ALREADY_SET=from file\n"))
        self.assertEqual(os.environ["ALREADY_SET"], "from shell")

    def test_missing_file_is_fine(self):
        self.assertEqual(dotenv_loader.load(Path("/nonexistent/.env")), {})


if __name__ == "__main__":
    unittest.main()
